apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: higress-console
  name: higress-console
  namespace: higress-system
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: higress-console
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: higress-console
    spec:
      containers:
      - env:
        - name: JAVA_HOME
          value: /usr/local/openjdk-18
        - name: LANG
          value: C.UTF-8
        - name: SPRING_PROFILES_ACTIVE
          value: k8s
        image: higress-registry.cn-hangzhou.cr.aliyuncs.com/higress/console:0.0.1
        imagePullPolicy: Always
        name: higress-console
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/run/secrets/access-token
          name: access-token
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: access-token
        projected:
          defaultMode: 420
          sources:
          - serviceAccountToken:
              audience: istio-ca
              expirationSeconds: 3600
              path: token
---
apiVersion: v1
kind: Service
metadata:
  name: higress-console
  namespace: higress-system
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: higress-console
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: higress-console
  namespace: higress-system
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: higress-console
            port:
              number: 8080
